create table "public"."zuzalu_donations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "address" text not null,
    "email" text not null,
    "amount" text
);


alter table "public"."zuzalu_donations" enable row level security;

CREATE UNIQUE INDEX zuzalu_donations_pkey ON public.zuzalu_donations USING btree (id);

alter table "public"."zuzalu_donations" add constraint "zuzalu_donations_pkey" PRIMARY KEY using index "zuzalu_donations_pkey";


create policy "Allow insert for everybody"
on "public"."zuzalu_donations"
as permissive
for insert
to public
with check (true);
