// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/react-web/lib/host";

import { useRouter } from "next/router";
import { Hyperboard } from "@/components/hyperboard";

function Homepage() {
  // Use PlasmicHomepage to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicHomepage are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicHomepage is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // Next.js Custom App component
  // (https://nextjs.org/docs/advanced-features/custom-app).
  return (
    <ph.PageParamsProvider
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <Hyperboard
        data={[
          {
            id: "a",
            name: "Test",
            image:
              "https://img.freepik.com/free-vector/gradient-book-logo-with-slogan_23-2148832096.jpg?t=st=1693356627~exp=1693357227~hmac=a7d4c9eda4a0960eba551e457d5e1169771379b94461f5f7710ea3304ab9a6fc",
            value: 2,
          },
          {
            id: "b",
            name: "Test",
            image:
              "https://img.freepik.com/free-vector/gradient-book-logo-with-slogan_23-2148832096.jpg?t=st=1693356627~exp=1693357227~hmac=a7d4c9eda4a0960eba551e457d5e1169771379b94461f5f7710ea3304ab9a6fc",
            value: 2,
          },
          {
            id: "c",
            name: "Test",
            image:
              "https://img.freepik.com/free-vector/gradient-book-logo-with-slogan_23-2148832096.jpg?t=st=1693356627~exp=1693357227~hmac=a7d4c9eda4a0960eba551e457d5e1169771379b94461f5f7710ea3304ab9a6fc",
            value: 1,
          },
          {
            id: "d",
            name: "Test",
            image:
              "https://img.freepik.com/free-vector/gradient-book-logo-with-slogan_23-2148832096.jpg?t=st=1693356627~exp=1693357227~hmac=a7d4c9eda4a0960eba551e457d5e1169771379b94461f5f7710ea3304ab9a6fc",
            value: 1,
          },
        ]}
      />
    </ph.PageParamsProvider>
  );
}

export default Homepage;
